### ISSUE TITLE
Getting Error - npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by eindiainfohub** [ryanmurakami/trash-panda-buffet#13]
npm ERR! code ELIFECYCLE
--
182 | npm ERR! errno 2
183 | npm ERR! trash-panda-buffet@2.0.0 build:client: `webpack --config ./src/client/webpack.prod.config.js`
184 | npm ERR! Exit status 2
185 | npm ERR!
186 | npm ERR! Failed at the trash-panda-buffet@2.0.0 build:client script.
187 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
188 |  
189 | npm ERR! A complete log of this run can be found in:
190 | npm ERR!     /root/.npm/_logs/2020-10-11T16_33_58_723Z-debug.log
191 | npm ERR! code ELIFECYCLE
192 | npm ERR! errno 2
193 | npm ERR! trash-panda-buffet@2.0.0 deploy:client: `npm run build:client && serverless client deploy --no-confirm`
194 | npm ERR! Exit status 2
195 | npm ERR!
196 | npm ERR! Failed at the trash-panda-buffet@2.0.0 deploy:client script.
197 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
198 |  
199 | npm ERR! A complete log of this run can be found in:
200 | npm ERR!     /root/.npm/_logs/2020-10-11T16_33_58_732Z-debug.log
201 | npm ERR! code ELIFECYCLE
202 | npm ERR! errno 2
203 | npm ERR! trash-panda-buffet@2.0.0 deploy: `npm run deploy:aws && npm run deploy:client && npm run deploy:data`
204 | npm ERR! Exit status 2
205 | npm ERR!
206 | npm ERR! Failed at the trash-panda-buffet@2.0.0 deploy script.
207 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
208 |  
209 | npm ERR! A complete log of this run can be found in:
210 | npm ERR!     /root/.npm/_logs/2020-10-11T16_33_58_747Z-debug.log
211 |  
212 | [Container] 2020/10/11 16:33:58 Command did not exit successfully npm run deploy exit status 2
213 | [Container] 2020/10/11 16:33:58 Phase complete: BUILD State: FAILED
214 | [Container] 2020/10/11 16:33:58 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run deploy. Reason: exit status 2

**Comment by ryanmurakami** [comment]
Looks like this may be an issue with the build, probably the dependencies. Can you try just running `npm run build:client` and see if it finishes?

**Comment by eindiainfohub** [comment]
Same Error sir, might be an issue with this file :- `webpack --config ./src/client/webpack.prod.config.js`


npm ERR! code ELIFECYCLE
--
185 | npm ERR! errno 2
186 | npm ERR! trash-panda-buffet@2.0.0 build:client: `webpack --config ./src/client/webpack.prod.config.js`
187 | npm ERR! Exit status 2
188 | npm ERR!
189 | npm ERR! Failed at the trash-panda-buffet@2.0.0 build:client script.
190 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
191 |  
192 | npm ERR! A complete log of this run can be found in:
193 | npm ERR!     /root/.npm/_logs/2020-10-12T04_52_24_276Z-debug.log
194 | npm ERR! code ELIFECYCLE
195 | npm ERR! errno 2
196 | npm ERR! trash-panda-buffet@2.0.0 deploy:client: `npm run build:client && serverless client deploy --no-confirm`
197 | npm ERR! Exit status 2
198 | npm ERR!
199 | npm ERR! Failed at the trash-panda-buffet@2.0.0 deploy:client script.
200 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
201 |  
202 | npm ERR! A complete log of this run can be found in:
203 | npm ERR!     /root/.npm/_logs/2020-10-12T04_52_24_293Z-debug.log
204 |  
205 | [Container] 2020/10/12 04:52:24 Command did not exit successfully npm run deploy:aws && npm run deploy:client && npm run deploy:data exit status 2
206 | [Container] 2020/10/12 04:52:24 Phase complete: BUILD State: FAILED
207 | [Container] 2020/10/12 04:52:24 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run deploy:aws && npm run deploy:client && npm run deploy:data. Reason: exit status 2

**Comment by ryanmurakami** [comment]
Hmm.. yeah, I agree it probably has something to do with webpack. Can you make sure you're on Node.js v 12 (I haven't tested 14 yet), and that your dependencies haven't been updated?

**Comment by eindiainfohub** [comment]
This is buildspec.yml file.


version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      #- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
      - npm ci
      - npm install
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`      
      - npm run deploy
  post_build:
    commands:
          - echo Build completed on `date`

**Comment by ryanmurakami** [comment]
Sorry, the buildspec doesn't help at all. Have you tried just running the command locally instead of in a container? The build logs don't give any insight into the error.

**Comment by eindiainfohub** [comment]
Hello sir,

Issue resolved --
in buildspec.yml  - file
updated after npm install one more line -- npm update && npm audit fix --force

and update all package version in package.json file and also in serverless.yml file

now it works without any error.

Thanks sir
