### ISSUE TITLE
Error loading client after deploy

### ISSUE THREAD

**Issue by Jarret13** [ryanmurakami/trash-panda-buffet#19]
Hi Ryan, 

There seems to be an error with the javascript file that gets built and deployed for the client.  The apis are working fine and the javascript and css files are successfully downloaded from the CDN but then getting a blank screen when I try to hit the main endpoint and seeing this error in the dev tools console: 

Uncaught SyntaxError: Invalid or unexpected token   main.js:2

Here is what it's complaining about in the js file (only copying a small snippet where the syntax error starts because the file is large): 

Qt=zt({Ã€:"A",Ã:"A",Ã‚:"A",Ãƒ:"

It appears to be a character encoding issue.  For comparison, this is what the same snippet from my main.js file in my /dist folder looks like: 

Qt=zt({À:"A",Á:"A",Â:"A",Ã:"A"

For context, I'm on MacOS BigSur and using Node LTS version 14.16.1 and NPM version 6.14.12

**Comment by ryanmurakami** [comment]
Hi @Jarret13, thanks for posting the issue! I'm replicating the same thing. It looks like the issue has something to do with the encoding coming from CloudFront. Either when it's being uploaded, or when it's being downloaded. It'll take me a little longer to figure it out but I'll keep troubleshooting it.

**Comment by AdrianHL** [comment]
I have verified the file directly in S3 and the content is ok there, so it looks like the encoding issue has to be in CloudFront.
