### ISSUE TITLE
S3 buckets not available

### ISSUE THREAD

**Issue by sapienHero7** [ryanmurakami/trash-panda-buffet#2]
This is a great tutorial, Ryan, but unfortunately when it came time to run and deploy the application, I kept getting the following errors.  To be clear I was able to deploy the application to AWS and follow most of the tutorial, but I really want to see that Trash Panda UI.

Error after trying running deploy:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trash-panda-buffet@2.0.0 deploy:client: `npm run build:client && serverless client deploy --no-confirm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trash-panda-buffet@2.0.0 deploy:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/#####username/ .npm/_logs/2020-03-15T01_23_11_416Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trash-panda-buffet@2.0.0 deploy: `npm run deploy:aws && npm run deploy:client && npm run deploy:data`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trash-panda-buffet@2.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Error trying to navigate to the main url listed and used in the tutorial

{"message":"The specified bucket does not exist","code":"NoSuchBucket","region":null,"time":"2020-03-15T01:26:05.648Z","requestId":"ID123","extendedRequestId":"key123=","statusCode":404,"retryable":false,"retryDelay":42.35385663490043}

**Comment by ryanmurakami** [comment]
Hi @sapienHero7! 

Sorry you're having trouble! Sounds like the upload bucket isn't being created. Try creating the bucket found at line https://github.com/ryanmurakami/trash-panda-buffet/blob/4f54f49cc77cd189c2b8381329a9a3f5ba740c06/serverless.yml#L8 manually. It's possible it could be because the bucket already exists somewhere else.

Let me know!
