### ISSUE TITLE
Free tier does not include your db size

### ISSUE THREAD

**Issue by varjmes** [ryanmurakami/trash-panda-buffet#4]
Hey Ryan,

I took your course at the beginning of last month, it was super useful, thank you.
Unfortunately I just received a charge of 33 dollars to my account for using RDS. I thought this was covered by the free tier, which it is, but only for db.micro and you use db.large in your serverless file which I must have missed because I wasn't familiar enough at the time.

Just thought I'd let you know so you can change the db instance you use where possible.

Thanks again for the course!

**Comment by ryanmurakami** [comment]
Hi James,

Oh no! I totally missed that. I'm really sorry that happened. I'll get that updated in the course. Thanks so much for letting me know!

Ryan

**Comment by ryanmurakami** [comment]
After doing some research, it looks like Aurora does not work in the free tier. I'll need to add a note to that in the course. Sorry again about the unexpected charges!
